### ISSUE TITLE
ARM64 Windows support needs tests

### ISSUE THREAD

**Issue by jkunkee** [refack/GYP#26]
Now that support for ARM64 Windows ASM has been added, it should have accompanying tests. 

See discussion here: https://github.com/refack/GYP/pull/23

**Comment by jkunkee** [comment]
I started on this, but stopped when the existing Hello World tests (test/hello) fail due, I think, to an msbuild update. See:
https://github.com/jkunkee/GYP/tree/arm64-win-tests
https://github.com/jkunkee/GYP/tree/gh-pages

**Comment by refack** [comment]
I'm working bottom up, so I've added an `msvs-mock` test format that only generates the project files and with some tests validates their content (it does actualy try to run MSBuild).
You can run it with:
```
set GYP_MSVS_VERSION=2017
python gyptest.py -f msvs-mock test\actions-bare\gyptest-bare.py
```

**Comment by refack** [comment]
@jkunkee I've fixed MSVS testing with Python2 in latest master.

**Comment by jkunkee** [comment]
With Python 2, I'm still getting

```
File "C:\node\GYP\pylib\gyp\MSVS\MSVSVersion.py", line 9, in <module>
    from typing import Dict
```

I'm not blocked, though, since I can use Python 3.

Also, if it helps, the ARM64 compiler is x64 or x86, so the only thing testing ARM64 projects can't do is actually run the outputs.
